[package]
name = "rr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
lazy_static = "1.4.0"
num-traits = "0.2.14"
serde_json = "1.0.79"
